### ISSUE TITLE
Checkout agreements error for logged in customers

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/buckaroo-magento2#12]
When I use a logged in customer and have checkout agreements mode set to manual (non-auto agree) the checkout will fail with Buckaroo payment options. I receive an error message I need to agree with terms and conditions while I did check the checkbox.

**Comment by tig-jaspersmits** [comment]
Hi Rik,

I just tested this and i'm able to reproduce this error. You can follow the progression of the ticket on our backlog trough this url: https://jira.tig.nl/projects/BUCKM2/issues/BUCKM2-158

Kind regards,

Jasper
TIG

**Comment by rikwillems** [comment]
Hi Jasper,

I found that the same error occures for custom modules that add a field to the billing / payment method step. Like a order comment module. It throws the same error when the extra data is send along.

**Comment by tig-jaspersmits** [comment]
Hi Rik,
I will add it to the issue on the backlog.

Kind regards,
Jasper
TIG

**Comment by rikwillems** [comment]
Dear @tig-jaspersmits do you have any idea when this will be fixed? It is really quite annoying for customers.

**Comment by tig-jaspersmits** [comment]
Hi Rik,

It seems that the reaction my colleague gave on the issue on our backlog was not set to public. But this is a Magento related bug: https://github.com/magento/magento2/issues/11885

Even though this issue is only related to PayPal, it occurs with many other payment methods. I see that another developer created a solution for other payment methods. I will inform my colleague about this so he can revisit the problem. 

Once i have more information i will let you know immediately.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Rik,

Just discussed this. But this requires modification in the core Magento files. We don't prefer releasing a fix because this functionality was broken in a Magento release. But what i will do is discuss this with Buckaroo if we can invest some time in developing a temporary fix once Magento fixed this permanently.

I will get back on this as soon as possible.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Rik,

Sorry that i get back to you on this very late. 
Buckaroo recommended to use automatic terms and conditions for now instead of manual.
The issue is still on our backlog and Buckaroo can still decide if they want to do something with this.

Kind regards,
Jasper
TIG
