### ISSUE TITLE
Issue Afterpay payment method

### ISSUE THREAD

**Issue by jorgmaijen** [tig-nl/buckaroo-magento2#17]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento extension)

---

### Description of your *issue*, suggested solution and other information

When a customer wants to place an order and choose the afterpay method then they are not able to finish the order. The button to complete the order doesn't work. It looks like the issue is caused by the option to choose male or female. 

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by tig-jaspersmits** [comment]
Hi Jorg,

Thank you for submitting this report.
I hope you could provide me some more information about this. 

- What Magento version are you running?
- What is the version number of the Buckaroo extension?
- Can you reproduce this on a clean Magento environment with only the Buckaroo extension installed?

This problem is unknown to us. If you want us to test and troubleshoot this in your Magento webshop i recommend contacting Buckaroo about this. They will try to solve the problem with you and if they can't provide a solution they will forward it to us. You can send an email to support@buckaroo.nl or call Buckaroo on phone number 030-711 5000.

Kind regards,

Jasper 
TIG
