### ISSUE TITLE
PaypalSellersProtection/Push causes error: Invalid eligibility type

### ISSUE THREAD

**Issue by esseremmerik** [tig-nl/buckaroo-magento2#41]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension. 1.7.4.RC-1

---
- [X] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
---

PaypalSellersProtection/Push causes error: Invalid eligibility type

Error in exception log:
[2018-11-07 15:58:26] main.CRITICAL: Report ID: webapi-5be30ba281fba; Message: Invalid eligibility type. {"exception":"[object] (Exception(code: 0): Report ID: webapi-5be30ba281fba; Message: Invalid eligibility type. at /xxx/vendor/magento/framework/Webapi/ErrorProcessor.php:205, InvalidArgumentException(code: 0): Invalid eligibility type. at /xxx/vendor/tig/buckaroo/Model/Service/Plugin/PaypalSellersProtection/Push.php:120)"} []

### If the purpose of your issue is a *bug report*
I expect no error in the exception log when processing an invalid eligibility type in the push.

**Comment by tig-jaspersmits** [comment]
Hi @esseremmerik,

Thank you for your report. When does this error happen exactly? Do i just have to place an order trough PayPal for this to show up in the logs?

Looking forward to your response.

Kind regards,

Jasper
TIG

**Comment by fazed** [comment]
Hi @tig-jaspersmits,

I have some additional information regarding this issue, since we see the message every 5 minutes in the exception log. The given error message doesn't provide much clarity on the matter, so I've added the passed eligibility type(s) to the exception message.

Apparently the Buckaroo response passes multiple types on a single line, which are comma separated. See the message below for more information.

`[2018-11-27 11:24:12] main.CRITICAL: Report ID: webapi-5bfd295c0621c; Message: Invalid eligibility type: ItemNotReceivedEligible,UnauthorizedPaymentEligible {"exception":"[object] (Exception(code: 0): Report ID: webapi-5bfd295c0621c; Message: Invalid eligibility type: ItemNotReceivedEligible,UnauthorizedPaymentEligible at /xxx/vendor/magento/framework/Webapi/ErrorProcessor.php:205, InvalidArgumentException(code: 0): Invalid eligibility type: ItemNotReceivedEligible,UnauthorizedPaymentEligible at /xxx/vendor/tig/buckaroo/Model/Service/Plugin/PaypalSellersProtection/Push.php:120)"} []`

The perpetuator is the following line:
`ItemNotReceivedEligible,UnauthorizedPaymentEligible`

Just like @esseremmerik reported, as far as we know it only occurs when payments are made with PayPal. We're also not sure how to reproduce since it only occurs on the live shop and placing order(s) there is not an option.

Could this be hotfixed please, since its flooding the exception log.

Regards,

Bob Horvers
Flashpoint BV

**Comment by tig-robertgrundeken** [comment]
The PR #47 is added in release v1.8.0 
https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.8.0
