### ISSUE TITLE
Success page 'sometimes' shows error

### ISSUE THREAD

**Issue by thioz** [tig-nl/buckaroo-magento2#5]
One of our clients 'sometimes' experiences a bug that shows the 'Unfortunately an error occurred while processing your payment...' message on the success page, while the payment is successfully done. 

I cannot reproduce it and looking at the code it seems almost impossible for that to happen, but I would like your take on how this might occur

**Comment by tig-jaspersmits** [comment]
Hi Thioz,

I am uncertain if this is related to this issue: https://github.com/tig-nl/buckaroo-magento2/issues/6 . Could you let me know? Because if it's related there is no need for me to create a separate issue.

Otherwise it is hard for me to say what causes this. I can investigate this for you but in that case it is better contact Buckaroo directly. They can decide if they want us to investigate this further. 

I can give you the contact information if you need it, but if it is related it might not be necessary to contact them.

Kind regards,

Jasper
TIG
