### ISSUE TITLE
Malfunction in script

### ISSUE THREAD

**Issue by Luciferiix** [tig-nl/buckaroo-magento2#57]
### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [x] Other

---

### Malfunction in script ###

[redacted]

[redacted]

```
<script>
[redacted]
</script>
```

[redacted]

```
[redacted]
```

[redacted]

```
[redacted]
```

### If the purpose of your issue is about anything else, please describe your issue here
- Controller: I return a page when a KEY is given.
- Block: The viewModel returns the KEY unchecked.
- Template: Return the Key param as plaintext.

**Comment by tig-robertgrundeken** [comment]
@Luciferiix thanks for pointing this out. We are currently investigating this. I changed some texts to protect against automated crawlers.

**Comment by tig-dennisvanderhammen** [comment]
As my colleague mentioned, thank you for pointing out this issue.

He notified me that you also send the contents of your issue to his e-mail. Due to the nature if this issue report, we have redacted parts of this issue. We'll keep contact with you through e-mail and try to resolve this as soon as we can.

**Comment by Luciferiix** [comment]
Thanx !
